### ISSUE TITLE
Time label

### ISSUE THREAD

**Issue by MisterBianco** [molnarmark/spinny#7]
Would there be a succinct way to add a time label to the spinner so that I can show how long a task has been running?

And after completion show how long the spinner executed for?

**Comment by ghost** [comment]
@MisterBianco I implemented initial time support in https://github.com/Yardanico/spinny/tree/addtimes (based on my changes in https://github.com/molnarmark/spinny/pull/8), you basically have one boolean to toggle it on/off and then it will "just work" :tm: 
```nim
import spinny, os

var spinner3 = newSpinny("I'm custom.", Earth, true)
spinner3.start()

# do some magnificent work here
for x in countup(1, 5):
  sleep(1000)

spinner3.success("Looks like it's working!")
```

![](https://i.imgur.com/preMQ3V.png)
![](https://i.imgur.com/u9XITFP.png)

Do you have any thoughts on how it should be formatted and where it should be placed?

**Comment by MisterBianco** [comment]
Awesome! Thank you @Yardanico

**Comment by ghost** [comment]
@MisterBianco you can now install my fork with "nimble install spinny" :) and check https://github.com/Yardanico/spinny
